In [1]:
import numpy as np
from numpy import *

from numpy.random import rand

In [9]:

#for i in range(1,5):
    
    #A = matrix_example(i)  # Should work for matrices of Types I, II, III and IV. 

    #Q,R = QR(A,'full')
    #display_mat("A = ",A)
    #display_mat("Q = ",Q)
    #display_mat("R = ",R)
    #display_mat("QR = ",Q@R)
    #display_mat("Q^TQ = ",Q.T@Q)

In [10]:
A = matrix_example(1)   
Q,R = QR(A,'full')
display_mat("A1 = ",A)
display_mat("Q = ",Q)
display_mat("R = ",R)
display_mat("QR = ",Q@R)
display_mat("Q^TQ = ",Q.T@Q)

A = matrix_example(2)   
Q,R = QR(A,'full')
display_mat("A2 = ",A)
display_mat("Q = ",Q)
display_mat("R = ",R)
display_mat("QR = ",Q@R)
display_mat("Q^TQ = ",Q.T@Q)

A1 = 


array([[  1.00000000,   2.00000000,  -1.00000000],
       [  3.00000000,   7.00000000,   4.00000000],
       [  5.00000000,   6.00000000,   4.00000000]])


Q = 


array([[  0.16903085,   0.16426846,  -0.97182532],
       [  0.50709255,   0.83100515,   0.22866478],
       [  0.84515425,  -0.53145678,   0.05716620]])


R = 


array([[  5.91607978,   8.95863510,   5.23995638],
       [  0.00000000,   2.95683228,   1.03392501],
       [  0.00000000,   0.00000000,   2.11514922]])


QR = 


array([[  1.00000000,   2.00000000,  -1.00000000],
       [  3.00000000,   7.00000000,   4.00000000],
       [  5.00000000,   6.00000000,   4.00000000]])


Q^TQ = 


array([[  1.00000000,  -0.00000000,  -0.00000000],
       [ -0.00000000,   1.00000000,  -0.00000000],
       [ -0.00000000,  -0.00000000,   1.00000000]])


A2 = 


array([[  1.00000000,   2.00000000],
       [  3.00000000,   4.00000000],
       [  5.00000000,  -1.00000000]])


Q = 


array([[  0.16903085,   0.40318739,   0.89937117],
       [  0.50709255,   0.74688811,  -0.43013404],
       [  0.84515425,  -0.52877035,   0.07820619]])


R = 


array([[  5.91607978,   1.52127766],
       [  0.00000000,   4.32269757],
       [  0.00000000,   0.00000000]])


QR = 


array([[  1.00000000,   2.00000000],
       [  3.00000000,   4.00000000],
       [  5.00000000,  -1.00000000]])


Q^TQ = 


array([[  1.00000000,   0.00000000,  -0.00000000],
       [  0.00000000,   1.00000000,   0.00000000],
       [ -0.00000000,   0.00000000,   1.00000000]])

In [11]:
A = matrix_example(3)   
Q,R = QR(A,'full')
display_mat("A3 = ",A)
display_mat("Q = ",Q)
display_mat("R = ",R)
display_mat("QR = ",Q@R)
display_mat("Q^TQ = ",Q.T@Q)

A = matrix_example(4)   
Q,R = QR(A,'full')
display_mat("A4 = ",A)
display_mat("Q = ",Q)
display_mat("R = ",R)
display_mat("QR = ",Q@R)
display_mat("Q^TQ = ",Q.T@Q)

A3 = 


array([[  1.00000000,   2.00000000,  -1.00000000,   7.00000000],
       [  3.00000000,   7.00000000,   4.00000000,   9.00000000]])


Q = 


array([[  0.31622777,  -0.94868330],
       [  0.94868330,   0.31622777]])


R = 


array([[  3.16227766,   7.27323862,   3.47850543,  10.75174404],
       [  0.00000000,   0.31622777,   2.21359436,  -3.79473319]])


QR = 


array([[  1.00000000,   2.00000000,  -1.00000000,   7.00000000],
       [  3.00000000,   7.00000000,   4.00000000,   9.00000000]])


Q^TQ = 


array([[  1.00000000,   0.00000000],
       [  0.00000000,   1.00000000]])


A4 = 


array([[  1.00000000,   3.00000000,   5.00000000],
       [  1.00000000,   1.00000000,   1.00000000],
       [  2.00000000,   4.00000000,   6.00000000]])


Q = 


array([[  0.40824829,   0.70710678,   0.57735027],
       [  0.40824829,  -0.70710678,   0.57735027],
       [  0.81649658,   0.00000000,  -0.57735027]])


R = 


array([[  2.44948974,   4.89897949,   7.34846923],
       [  0.00000000,   1.41421356,   2.82842712],
       [  0.00000000,   0.00000000,   0.00000000]])


QR = 


array([[  1.00000000,   3.00000000,   5.00000000],
       [  1.00000000,   1.00000000,   1.00000000],
       [  2.00000000,   4.00000000,   6.00000000]])


Q^TQ = 


array([[  1.00000000,   0.00000000,  -0.00000000],
       [  0.00000000,   1.00000000,  -0.00000000],
       [ -0.00000000,  -0.00000000,   1.00000000]])

## Problem #4 : Uniqueness of the QR factorization

<hr style="border-width:2px; border-color:black"></hr>

Compare your results above to the QR factorization routine in NumPy.  What can you say about the uniqueness of the reduced and full QR factorization?  Can you comment on the NumPy routine? 




In [12]:
# I wonder why np.linalg.qr sometimes displays full matrices for mode = 'reduced'


A = matrix_example(2)

q,r = np.linalg.qr(A)

display_mat("q = ",q)
display_mat("r = ",r)
A = matrix_example(4)

q,r = np.linalg.qr(A)

display_mat("q = ",q)
display_mat("r = ",r)

q = 


array([[ -0.16903085,  -0.40318739],
       [ -0.50709255,  -0.74688811],
       [ -0.84515425,   0.52877035]])


r = 


array([[ -5.91607978,  -1.52127766],
       [  0.00000000,  -4.32269757]])


q = 


array([[ -0.40824829,   0.70710678,  -0.57735027],
       [ -0.40824829,  -0.70710678,  -0.57735027],
       [ -0.81649658,  -0.00000000,   0.57735027]])


r = 


array([[ -2.44948974,  -4.89897949,  -7.34846923],
       [  0.00000000,   1.41421356,   2.82842712],
       [  0.00000000,   0.00000000,   0.00000000]])

Except for the difference in the signs on the entries of $Q$ and $R$, the
QR factorization routine in NumPy gives the same results as the corresponding reduced or full QR factorization for all the types.

For types I and II that is matrices with $m\geq n$ and full column rank, both the reduced and full QR factorization will always be unique. However, for types III and IV  the reduced QR factorization is unique but the full QR factorization is not unique since we get other columns of $Q$ from the null space of $Q^T$ and also because the columns in the original matrices are not linearly independent.

## Problem #5 

<hr style="border-width:2px; border-color:black"></hr>

Suppose we have planes $P^{(1)}$ and $P^{(2)}$ in $\mathbb R^3$ given by 

\begin{equation}
P^{(1)} = \langle \mathbf x^{(1)}, \mathbf y^{(1)}\rangle, \qquad 
P^{(2)}\langle \mathbf x^{(2)}, \mathbf y^{(2)}\rangle
\end{equation}

where $\mathbf x^{(1)}, \mathbf y^{(1)} \in \mathbb R^3$ are linearly independent and  $\mathbf x^{(2)}, \mathbf y^{(2)} \in \mathbb R^3$ are linearly independent. 

**(a)** How can you find $P^{(1)} \cap P^{(2)}$ using a $QR$ decomposition?  **Hint:** Use the full $QR$ decomposition.  

**(b)** Find the intersection of the planes described by the following two sets of vectors. 

\begin{equation}
\mathbf x^{(1)} = \begin{bmatrix} 1\\2\\-1 \end{bmatrix}, \qquad
\mathbf y^{(1)} = \begin{bmatrix} 3\\0\\5 \end{bmatrix}, \qquad
\mathbf x^{(2)} = \begin{bmatrix} 7\\-3\\1 \end{bmatrix}, \qquad
\mathbf y^{(2)} = \begin{bmatrix} 0\\4\\8 \end{bmatrix}
\end{equation}

**(c)** Construct projections $P_1$ onto $P^{(1)}$ and $P_2$ onto $P^{(2)}$ and show that for some $\mathbf v \in P^{(1)} \cap P^{(2)}$, we have $P_1 \mathbf v = P_2 \mathbf v = \mathbf v$.  Verify the result by displaying 

\begin{equation}
\Vert P_1 \mathbf v - \mathbf v \Vert, \qquad \Vert P_2 \mathbf v - \mathbf v \Vert
\end{equation}

**Hint:** You only need to verify this numerically for one $\mathbf v$.  Use the $QR$ decompositions to easily compute the projections.


### Solution
**(a)**


Let $P$= $P^{(1)}$ $\cap$ $P^{(2)}$.
This means that $P$ is a straight line which is orthogonal to the cross products $x^{(1)}\times y^{(1)}$ and $x^{(2)}\times y^{(2)}$.

From $QR$ decomposition, we notice that the columnns $q_j$ for $j>n$(number of columns) of matrix $Q$ are in the range(A). This means that the third column of $Q$ with respect to plane $P^{(1)}$  should be equivalent to $x^{(1)}\times y^{(1)}$, similarly  the third column of $Q$ with respect to plane $P^{(2)}$  should be equivalent to $x^{(2)}\times y^{(2)}$.
The $QR$ decompositon of the two third columns from the $Q's$ with respect to two planes above results into a vector $v\in P$ and this occupies the last column of this new Q and $v$ is orthogonal to the first two columns of new Q. 


**(b)**

In [13]:
#
P_1 = np.array(np.mat('1,3;2,0; -1,5'),dtype='float') #plane 1
P_2 = np.array(np.mat('7,0;-3,4;1,8'),dtype='float') #plane 2

q1,r1 = QR(P_1,'full')
q2,r2 = QR(P_2,'full')

m,n =q1.shape

q13 = q1[:,n-1:n]
q23 = q2[:,n-1:n]

qo = np.column_stack([q13,q23])
q,r = QR(qo,'full')
 # The third column of q gives the vector in the intersection of the two planes
display_mat("The intersection P = ",q[:,n-1:n])

The intersection P = 


array([[  0.57735027],
       [  0.11547005],
       [  0.80829038]])

**(c)**

In [14]:
v = q[:,n-1:n]
P1 = q1[:,0:2]@q1[:,0:2].T #Projection P1
P2 = q2[:,0:2]@q2[:,0:2].T #Projection P2
display_mat("Projection P_1 onto P^(1) = ",P1)
display_mat("Projection P_2 onto P^(2) = ",P2)
display_mat("v = ",v)
display_mat("P1v = ",P1@v)
display_mat("P2v = ",P2@v)
display_mat(" ‖P1v-v‖ = ",np.linalg.norm(P1@v-v))
display_mat("‖P2v-v‖ = ",np.linalg.norm(P2@v-v))


Projection P_1 onto P^(1) = 


array([[  0.50000000,   0.40000000,   0.30000000],
       [  0.40000000,   0.68000000,  -0.24000000],
       [  0.30000000,  -0.24000000,   0.82000000]])


Projection P_2 onto P^(2) = 


array([[  0.83333333,  -0.33333333,   0.16666667],
       [ -0.33333333,   0.33333333,   0.33333333],
       [  0.16666667,   0.33333333,   0.83333333]])


v = 


array([[  0.57735027],
       [  0.11547005],
       [  0.80829038]])


P1v = 


array([[  0.57735027],
       [  0.11547005],
       [  0.80829038]])


P2v = 


array([[  0.57735027],
       [  0.11547005],
       [  0.80829038]])


 ‖P1v-v‖ = 


1.0295784775289034e-15


‖P2v-v‖ = 


2.8609792490763985e-16

From above, since $\left \Vert P_1v-v \right \Vert = 0$ and $\left \Vert P_2v-v \right \Vert = 0$, then $P_1v=P_2v=v$. 